import { WidgetDefinition, WidgetType } from './types';

// Widget 注册表
export const WIDGET_REGISTRY: Record<WidgetType, WidgetDefinition> = {
  'order-book': {
    id: 'order-book',
    name: 'Order Book',
    nameZh: '订单簿',
    icon: '📊',
    category: 'trading',
    defaultSize: { width: 300, height: 400 },
    minSize: { width: 250, height: 300 },
    description: 'Cross-market order book with multi-exchange support',
    descriptionZh: '跨市场订单簿，支持多交易所',
  },
  'trading-chart': {
    id: 'trading-chart',
    name: 'Trading Chart',
    nameZh: '交易图表',
    icon: '📈',
    category: 'charts',
    defaultSize: { width: 600, height: 400 },
    minSize: { width: 400, height: 300 },
    description: 'Professional trading chart with drawing tools',
    descriptionZh: '专业交易图表，支持画线工具',
  },
  'quick-trade': {
    id: 'quick-trade',
    name: 'Quick Trade',
    nameZh: '快速交易',
    icon: '⚡',
    category: 'trading',
    defaultSize: { width: 300, height: 250 },
    minSize: { width: 250, height: 200 },
    description: 'Quick order entry panel',
    descriptionZh: '快速下单面板',
  },
  'positions': {
    id: 'positions',
    name: 'Positions',
    nameZh: '持仓',
    icon: '💼',
    category: 'trading',
    defaultSize: { width: 400, height: 300 },
    minSize: { width: 300, height: 200 },
    description: 'Current positions and P&L',
    descriptionZh: '当前持仓和盈亏',
  },
  'trade-history': {
    id: 'trade-history',
    name: 'Trade History',
    nameZh: '交易历史',
    icon: '📜',
    category: 'trading',
    defaultSize: { width: 400, height: 300 },
    minSize: { width: 300, height: 200 },
    description: 'Recent trade history',
    descriptionZh: '最近交易记录',
  },
  'ai-agent': {
    id: 'ai-agent',
    name: 'AI Agent',
    nameZh: 'AI 助手',
    icon: '🤖',
    category: 'ai',
    defaultSize: { width: 350, height: 500 },
    minSize: { width: 300, height: 400 },
    description: 'AI trading assistant with context awareness',
    descriptionZh: 'AI 交易助手，支持上下文分析',
  },
  'ai-research': {
    id: 'ai-research',
    name: 'AI Research',
    nameZh: 'AI 研究报告',
    icon: '📝',
    category: 'ai',
    defaultSize: { width: 400, height: 400 },
    minSize: { width: 350, height: 300 },
    description: 'AI-generated research reports',
    descriptionZh: 'AI 生成的研究报告',
  },
  'news-feed': {
    id: 'news-feed',
    name: 'News Feed',
    nameZh: '新闻推送',
    icon: '📰',
    category: 'news',
    defaultSize: { width: 350, height: 400 },
    minSize: { width: 280, height: 300 },
    description: 'Real-time news feed with filtering',
    descriptionZh: '实时新闻推送，支持筛选',
  },
  'youtube-embed': {
    id: 'youtube-embed',
    name: 'YouTube',
    nameZh: 'YouTube 视频',
    icon: '🎥',
    category: 'media',
    defaultSize: { width: 400, height: 300 },
    minSize: { width: 320, height: 240 },
    description: 'Embedded YouTube videos (Fed conferences, etc.)',
    descriptionZh: '嵌入 YouTube 视频（Fed 发布会等）',
  },
  'fed-watch': {
    id: 'fed-watch',
    name: 'FedWatch Tool',
    nameZh: 'FedWatch 工具',
    icon: '🏦',
    category: 'research',
    defaultSize: { width: 400, height: 350 },
    minSize: { width: 350, height: 280 },
    description: 'CME FedWatch rate probabilities',
    descriptionZh: 'CME FedWatch 利率概率表',
  },
  'market-overview': {
    id: 'market-overview',
    name: 'Market Overview',
    nameZh: '市场概览',
    icon: '🌐',
    category: 'data',
    defaultSize: { width: 350, height: 300 },
    minSize: { width: 280, height: 250 },
    description: 'Overview of popular markets',
    descriptionZh: '热门市场概览',
  },
  'watchlist': {
    id: 'watchlist',
    name: 'Watchlist',
    nameZh: '自选列表',
    icon: '⭐',
    category: 'data',
    defaultSize: { width: 300, height: 350 },
    minSize: { width: 250, height: 280 },
    description: 'Your watched markets',
    descriptionZh: '您关注的市场',
  },
  'portfolio-chart': {
    id: 'portfolio-chart',
    name: 'Portfolio Chart',
    nameZh: '组合图表',
    icon: '📊',
    category: 'charts',
    defaultSize: { width: 400, height: 300 },
    minSize: { width: 300, height: 200 },
    description: 'Portfolio equity curve',
    descriptionZh: '组合收益曲线',
  },
  'twitter-feed': {
    id: 'twitter-feed',
    name: 'Twitter/X Feed',
    nameZh: 'Twitter/X 动态',
    icon: '🐦',
    category: 'news',
    defaultSize: { width: 350, height: 400 },
    minSize: { width: 300, height: 300 },
    description: 'Embedded Twitter/X feed',
    descriptionZh: '嵌入 Twitter/X 动态',
  },
  'economic-calendar': {
    id: 'economic-calendar',
    name: 'Economic Calendar',
    nameZh: '经济日历',
    icon: '📅',
    category: 'research',
    defaultSize: { width: 350, height: 300 },
    minSize: { width: 300, height: 250 },
    description: 'Upcoming economic events',
    descriptionZh: '即将到来的经济事件',
  },
};

// 按分类获取 Widget
export function getWidgetsByCategory(category: WidgetCategory): WidgetDefinition[] {
  return Object.values(WIDGET_REGISTRY).filter((w) => w.category === category);
}

// 获取所有分类
export function getAllCategories(): { id: WidgetCategory; name: string; nameZh: string }[] {
  return [
    { id: 'trading', name: 'Trading', nameZh: '交易' },
    { id: 'charts', name: 'Charts', nameZh: '图表' },
    { id: 'ai', name: 'AI', nameZh: 'AI' },
    { id: 'news', name: 'News', nameZh: '新闻' },
    { id: 'research', name: 'Research', nameZh: '研究' },
    { id: 'data', name: 'Data', nameZh: '数据' },
    { id: 'media', name: 'Media', nameZh: '媒体' },
  ];
}

// 获取 Widget 定义
export function getWidgetDefinition(type: WidgetType): WidgetDefinition | undefined {
  return WIDGET_REGISTRY[type];
}
